version: "3.8"
volumes:
  db-store:
services:
  web:
    build: 
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
  db:
    build: 
      context: .
      dockerfile: ./db/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=slim_db
      - MYSQL_USER=slim_user
      - MYSQL_PASSWORD=slim_pass
      - MYSQL_ROOT_PASSWORD=root
